// This file is automatically generated. Do not edit it directly.
// CUSTOM: Added session storage adapter for "Remember Me" feature
// CUSTOM: Exported SUPABASE_URL and SUPABASE_ANON_KEY for streaming fetch calls (SEC-01 fix)
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { createSessionStorage } from '@/utils/sessionStorageAdapter';

export const SUPABASE_URL = "https://rptccafbujxprahkstmp.supabase.co";
export const SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJwdGNjYWZidWp4cHJhaGtzdG1wIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk3ODAyNjEsImV4cCI6MjA2NTM1NjI2MX0.LaHvHcyUSZjyeJhJIem5fpaLZ4JL1GVUmPL8Duy6_gs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_ANON_KEY, {
  auth: {
    storage: createSessionStorage(),
    autoRefreshToken: true,
    persistSession: true,
    detectSessionInUrl: true,
  }
});